services:
  node:
    container_name: node
    tty: true
    build: ./build/docker/node
    ports:
      - '5173:5173'
      - '4173:4173'
    volumes:
      - ./app:/app
    environment:
      - HOST=0.0.0.0
